export const companies = [
  { name: "Google", logo: "https://cdn.simpleicons.org/google" },
  { name: "Facebook", logo: "https://cdn.simpleicons.org/facebook" },
  { name: "Microsoft", logo: "https://cdn.simpleicons.org/microsoft" },
  { name: "Amazon", logo: "https://cdn.simpleicons.org/amazon" },
  { name: "Apple", logo: "https://cdn.simpleicons.org/apple" },
  { name: "Netflix", logo: "https://cdn.simpleicons.org/netflix" },
  { name: "Tesla", logo: "https://cdn.simpleicons.org/tesla" },
  { name: "Adobe", logo: "https://cdn.simpleicons.org/adobe" },
  { name: "Slack", logo: "https://cdn.simpleicons.org/slack" },
  { name: "Spotify", logo: "https://cdn.simpleicons.org/spotify" },
  { name: "GitHub", logo: "https://cdn.simpleicons.org/github" },
  { name: "PayPal", logo: "https://cdn.simpleicons.org/paypal" },
  { name: "Dropbox", logo: "https://cdn.simpleicons.org/dropbox" },
  { name: "Uber", logo: "https://cdn.simpleicons.org/uber" },
  { name: "Airbnb", logo: "https://cdn.simpleicons.org/airbnb" },
  { name: "Twitter", logo: "https://cdn.simpleicons.org/twitter" },
  { name: "LinkedIn", logo: "https://cdn.simpleicons.org/linkedin" },
  { name: "YouTube", logo: "https://cdn.simpleicons.org/youtube" },
  { name: "Instagram", logo: "https://cdn.simpleicons.org/instagram" },
  { name: "Reddit", logo: "https://cdn.simpleicons.org/reddit" },
];

export const partners = [
  { name : "acer", src: "/assets/partnersLogo/acer.svg"},
  { name : "amazonpay", src: "/assets/partnersLogo/amazonpay.svg"},
  { name : "americanexpress", src: "/assets/partnersLogo/americanexpress.svg"},
  { name : "shopify", src: "/assets/partnersLogo/shopify.svg"},
  { name : "asus", src: "/assets/partnersLogo/asus.svg"},
  { name : "githubpages", src: "/assets/partnersLogo/githubpages.svg"},
  { name : "hyundai", src: "/assets/partnersLogo/hyundai.svg"},
  { name : "mega", src: "/assets/partnersLogo/mega.svg"},
  { name : "messenger", src: "/assets/partnersLogo/messenger.svg"},
  { name : "pubg", src: "/assets/partnersLogo/pubg.svg"},
  { name : "shopee", src: "/assets/partnersLogo/shopee.svg"},
  { name : "stackoverflow", src: "/assets/partnersLogo/stackoverflow.svg"},
]